#!/bin/bash

echo "Content-type: text/plain; charset=iso-8859-1"
echo ""

MESSAGE=$(grep message webapp.conf |awk -F "=" '{print $2}'|tr -d \")

echo $MESSAGE
echo "Time is: $(date)"
echo "Docker id: $(cat /proc/self/cgroup|head -1|awk -F "/" '{print $3}')"
